# brew bundle

# Taps

tap homebrew/dupes
tap homebrew/games
tap homebrew/versions
tap josegonzalez/homebrew-php
tap phinze/homebrew-cask
tap caskroom/versions

# Installs

install git
install brew-cask
install osxfuse
install php55
install ruby
install python
install node
install composer
install mysql
install wget --enable-iri
install coda-cli
install bash
install postgresql9
install phpmyadmin

# Casks

cask install a-slower-speed-of-light
cask install adapter
cask install alfred
cask install backuploupe
cask install bartender
cask install calibre
cask install chameleon-ssd-optimizer
cask install cheatsheet
cask install cinch
cask install clamxav
cask install cleanmymac
cask install coda
cask install codekit
cask install debt-quencher
cask install deeper
cask install diffmerge
cask install duplicate-annihilator
cask install evernote
cask install f-lux
cask install filebot
cask install geekbench
cask install google-chrome
cask install grandperspective
cask install growlvoice
cask install handbrake
cask install id3-editor
cask install kext-utility
cask install kext-wizard
cask install launchcontrol
cask install liteicon
cask install mindnode-pro
cask install moneywell
cask install mou
cask install omnidisksweeper
cask install onyx
cask install pgadmin3
cask install picard
cask install pokertracker
cask install shuttle
cask install skitch
cask install skype
cask install slice-eq
cask install superduper
cask install thunderbird
cask install tickets
cask install tower
cask install transmit
cask install unetbootin
cask install virtualbox
cask install vlc
cask install zipeg
cask alfred link