# brew bundle

# Taps

tap homebrew/dupes
tap homebrew/games
tap homebrew/versions
tap josegonzalez/homebrew-php
tap phinze/homebrew-cask
tap caskroom/versions

# Installs

install git
install brew-cask
install osxfuse
install php55
install php55-xdebug
install ruby
install python
install node
install composer
install mysql
install mackup
install wget --enable-iri
install coda-cli
install postgresql9
install phpmyadmin
install bash-completion
install hr
install phpdoc


# Casks

cask install adapter
cask install alfred
cask install all2mp3
cask install bartender
cask install bittorrent-sync
cask install cheatsheet
cask install cinch
cask install clamxav
cask install cleanmymac
cask install coda
cask install codekit
cask install color-picker-pro
cask install crashplan
cask install dropbox
cask install deeper
cask install diffmerge
cask install evernote
cask install flux
cask install filebot
cask install fluid
cask install geekbench
cask install google-chrome
cask install google-drive
cask install grandperspective
cask install handbrake
cask install id3-editor
cask install insync
cask install launchcontrol
cask install liteicon
cask install mindnode-pro
cask install mou
cask install omnidisksweeper
cask install onyx
cask install shuttle
cask install skitch
cask install skype
cask install tower
cask install transmit
cask install unetbootin
cask install vagrant
cask install virtualbox
cask install vlc
cask install zipeg
